ALTER TABLE ai_runs
    ADD COLUMN IF NOT EXISTS provider_type VARCHAR(64) NOT NULL DEFAULT 'unknown',
    ADD COLUMN IF NOT EXISTS fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS fallback_reason TEXT,
    ADD COLUMN IF NOT EXISTS retrieval_status VARCHAR(32);
