spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.enterprise.ticketing: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

